Yuraposledov/shrks 21 меню в виде header
sharks-practicum/snap-hero pull request #19
Opened 2023-01-27 01:28 UTC by UnidentifiedRaccoon

### Какую задачу решаем
https://linear.app/kxnkxv-second/issue/SHRKS-21

### Описание задачи
Разработать сайт-меню

### Возникшие проблемы (и способы их решения)
Проблема; встраивание Sidebar в готовые страницы
Решение: hoс withSidebar + незначительные изменения в коде/стилях страниц

### Скриншоты/видео (если есть)
[{TODO_ Set title _) } - Google Chrome 2023-01-27 04-19-20.webm](https://user-images.githubusercontent.com/50448502/214989072-28bb1453-26d5-45fc-8015-1a44eb834971.webm)

2023-01-29 14:16 UTC, katkovergina approved these changes

2023-01-29 15:32 UTC, pitonoved requested changes

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/components/core/Sidebar/Sidebar.tsx
> +const Sidebar = ({titleLink = sidebarTitleLink, pageLinks = sidebarPageLinks, authLinks = sidebarAuthLink}: Props) => {
Не понял зачем нам тут пропсы. Мы же не будем переопределять titleLink например? Если нет, то проще импортнуть константы и использовать внутри компонента.

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/components/core/Sidebar/Sidebar.tsx
> +  const pageElements = pageLinks.map((link, i) => {
`pageElements` и `authElements` идентичны, напрашивается переиспользуемая функция, куда мы просто передаём массив authLinks или pageLinks

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/hooks/useAuth.ts
>          if (response) dispatch(setAuthorized({isAuthorized: true}))
А если нет response? Может выкинуть ошибку тогда? Хотя выглядит так, что метод `checkUser` должен всегда отдавать либо response, либо ошибку, тогда if тут лишний

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
Мы же можем глобально ориентироваться на `isAuthorized` из стейта? Тогда логика с isFirstCall лишняя, лучше смотреть на флаг из стора

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/pages/Forum/ForumPost/index.tsx
> +export default withSidebar(ForumPost)
Мне кажется, мы должны использовать глобальные шаблоны, и оборачивать в эти шаблоны на уровне роутинга. Ну типа у нас есть шаблон MainLayout или (PrivatLayout) - со слайдером и шапкой, внутри которого у нас находятся роуты со страницами соответствующего отображения.

2023-01-29 15:32 UTC, pitonoved commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
В таких кейсах лучше оборачивать await в try\catch

2023-01-29 15:40 UTC, UnidentifiedRaccoon commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
Да, я эту штуку в последнем комите докрутил 
```
export const signIn = createAsyncThunk(
  'user/signIn', async({data}: LoginParams) => {
    const response = await AuthController.signIn(data)
    if (response instanceof Error) {
      throw response
    }
  }
);
```

2023-01-29 15:49 UTC, UnidentifiedRaccoon commented on packages/client/src/app/pages/Forum/ForumPost/index.tsx
> +export default withSidebar(ForumPost)
![image](https://user-images.githubusercontent.com/50448502/215338010-266cfb80-4f67-4725-880d-ade2770d6a9e.png)

Правильно понимаю что предложение состоит в замене hoc на подобную конструкцию?
```
<Route path="/" element={<AuthorizedGuard page={<MainLayout><UIKit/></MainLayout>}/>}
```

2023-01-29 15:59 UTC, UnidentifiedRaccoon commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
Не понял что ты хотел сказать(

Логика такая: 
Мы смотрим на флаг. При старте приложения isAuthorized = false
При первом обращении к useAuth() выполняется useEffect(() => {}, [firstCall]). 
В нем запрашиваются данные пользователя. Если сервер вернул данные, значит юзер авторизован -> isAuthorized = true. Иначе остается значение по умолчанию (false)

Объясни подробней (если можешь, с примером кода) как оптимальное описать эту логику. Если моя логика не верна, опиши, как оно должно работать на твой взгляд

2023-01-29 16:00 UTC, pitonoved commented on packages/client/src/app/pages/Forum/ForumPost/index.tsx
> +export default withSidebar(ForumPost)
Да, что-то типо того. Можно также подумать применить шаблоны внутри AuthrizedGuard, если логика отображения связана. Только тогда это будет называться как-то типо PrivatPage

2023-01-29 16:00 UTC, UnidentifiedRaccoon commented on packages/client/src/app/hooks/useAuth.ts
>          if (response) dispatch(setAuthorized({isAuthorized: true}))
Да, есть такое, исправил

2023-01-29 16:04 UTC, UnidentifiedRaccoon commented on packages/client/src/app/components/core/Sidebar/Sidebar.tsx
> +  const pageElements = pageLinks.map((link, i) => {
Соглашусь

2023-01-29 16:06 UTC, UnidentifiedRaccoon commented on packages/client/src/app/components/core/Sidebar/Sidebar.tsx
> +const Sidebar = ({titleLink = sidebarTitleLink, pageLinks = sidebarPageLinks, authLinks = sidebarAuthLink}: Props) => {
Да, это рудимент. По началу хотел сделать универсальный компонент, поэтому прокидывал как пропсы.
Убрал

2023-01-29 16:14 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
Тут tricky moment
1. Про DTO рассказывали в 1 модуле. Data transfer object. В данном случае используется для обозначения типа объекта ```User``` пришедшего с сервера. Он отличается от типа ```User``` используемого на клинте.
2. Про микс нейминга. Тут вот не знаю как лучше. Если без Snake case, то ```To``` в середине становится плохо различимым UserDTOToUser (если с маленькой буквы писать, то зеркальная проблема  UsertoUserDTO)
3. Считаю что лучше не раздувать контролеры. Все что может быть вынесено, должно быть вынесено

2023-01-29 16:15 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserDTO_to_User.ts
> +    id: `${data.id}`,
![image](https://user-images.githubusercontent.com/50448502/215339499-a8f48147-6131-4b56-a163-b7d41cc2d28e.png)
С сервера приходит число, но на клиенте проще работать со строкой

2023-01-29 16:18 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/transport.ts
> +export const YandexAPI = 'https://ya-praktikum.tech/api/v2'
Наверное, но разве ее значение меняется в зависимости от окружения?
Если да, то можешь кратко описать use case

2023-01-29 16:23 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +    if (isResponseOk(response)) return UserDTO_to_User(response.data)
1. Да. Это флешбеки из университета. Исправил
2. Звучит правдоподобно

> transport.get должен под капотом обрабатывать ошибки, а возвращать промис с данными или стандартный объект ошибки

но с axios я раньше не работал и пока не смог найти такой возможности. Если есть ссылки на статьи или примеры кода, то поделись пожалуйста

2023-01-29 16:47 UTC, UnidentifiedRaccoon commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
И еще момент. Вызов signIn неявно обернут в try catch. Так что не совсем понимаю зачем оборачивать внутренний await в try catch 
Получается я сделаю костыль
```try {await} catch (e) throw e```

2023-01-29 18:47 UTC, UnidentifiedRaccoon commented on packages/client/src/app/pages/Forum/ForumPost/index.tsx
> +export default withSidebar(ForumPost)
Ок

2023-01-29 18:55 UTC, pitonoved commented on packages/client/src/app/Controllers/transport.ts
> +export const YandexAPI = 'https://ya-praktikum.tech/api/v2'
В данном проекте именно юрл яндекса, вероятно, нет. Но когда мы пилим свой бэк и раскатываем на разные контуры (локальный апи, dev, test, show, prod и пр.) то на каждом контуре у нас свой базовый урл к апишке, своя бд. Соответственно, лучше привести к единообразию. Но в данном проекте и именно в этой части не принципиально.

2023-01-29 18:59 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/transport.ts
> +export const YandexAPI = 'https://ya-praktikum.tech/api/v2'
>  раскатываем на разные контуры (локальный апи, dev, test, show, prod и пр.) то на каждом контуре у нас свой базовый урл к апишке

Понял. Звучит логично. Вынесу в env

2023-01-29 19:19 UTC, pitonoved commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +    if (isResponseOk(response)) return UserDTO_to_User(response.data)
Можно transport (я бы назвал прямо API) реализовать как объект или класс API, который будет содержать методы, вызывающие axios. Например, API.get(url, payload) будет вызывать axios.get, а ответ оборачивать в try\catch, где в catch ловим ошибку и обрабатываем все кейсы как нам нужно. Таким образом, где бы мы не применяли API.get\post и т.д., мы всегда будем получать данные в едином формате.  Сходу статью не нашел, но это один из подходов. А вообще я бы посмотрел в сторону saga, я думал мы через нее будем строить api.

2023-01-29 19:21 UTC, pitonoved commented on packages/client/src/app/Controllers/UserController/UserDTO_to_User.ts
> +    id: `${data.id}`,
В таком случае более декларативно было бы использовать `data.id.toString()`. Тогда сразу понятны намерения разработчика

2023-01-29 19:27 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserDTO_to_User.ts
> +    id: `${data.id}`,
Справедливо. Запомнил. Исправил

2023-01-29 19:30 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +    if (isResponseOk(response)) return UserDTO_to_User(response.data)
> класс API, который будет содержать методы, вызывающие axios.
Поработаю над этим

>  я бы посмотрел в сторону saga
я бы тоже посмотрел, будь чуть больше времени. Если таковое найдется изучу и перепишу

2023-01-29 19:36 UTC, pitonoved commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
Я ни в одном из проектов этой аббревиатуры не встречал, да и в принципе это же не явный термин, т.е. в разных компаниях может употребляться свой термин. Я бы назвал более понятно по смыслу, например `normalizeUserData`

По поводу "Все что может быть вынесено, должно быть вынесено" в целом согласен, но есть кейсы, когда должен быть баланс читабельности. Ну т.е. когда у нас файл на 10 строк, и нам нужно добавить обработку данных на 5 строк, то в данном случае это негативно сказывается на читабельности - приходится бежать в другой файл, смотреть что там происходит с данными. Ну это чисто моё наблюдение, холиварно и не принципиально конечно)

2023-01-29 19:37 UTC, pitonoved commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
Я о том, что тут ты создаешь переменную isFirstCall, но почему бы не смотреть сразу на isAuthorized?

2023-01-29 19:43 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
normalizeUserData вместо UserDTO_to_User?
Допустим, хотя это скорее маппинг данных чем нормализация. 
Но как в такой ситуации быть с обратной ситуацией User_to_UserDTO (как назвать такую ф-цию)

И какие тогда названия интерфейсов? UserServerData и UserData?

2023-01-29 19:49 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
> Ну т.е. когда у нас файл на 10 строк

Ну тут преждевременная оптимизация. Я заранее понимаю что там будут еще минимум запросы на смену пароля, аватарки и данных. Так что размер файла будет 40+ строк. Но да, заранее так не делать пожалуй не стоило

2023-01-29 19:55 UTC, pitonoved commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
`await AuthController.signIn(data)` - в data кривые данные\сервер упал\и т.д. - код прерывается, как если бы ты вызвал throw, соответственно следующая строка после await не выполнится, в данном случае (`return isResponseOk(response)...`). Это тот же промис

Зачем возвращать true в случае успешного выполнения? Это же промис, он либо resolve, либо reject. Т.е. в коде ты его просто обрабатываешь через then, или try\catch, тебе не нужно смотреть что вернулся true.

2023-01-29 20:09 UTC, pitonoved commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
> normalizeUserData вместо UserDTO_to_User? Допустим, хотя это скорее маппинг данных чем нормализация. Но как в такой ситуации как быть с обратной ситуацией User_to_UserDTO (как назвать такую ф-цию)
> 
> И какие тогда названия интерфейсов? UserServerData и UserData?

normalizeUserData это первое что в голову пришло) Главный смысл - чтобы любому коллеге было понятно из названия. Например, mapUserDataFromResponse \ mapUserDataToRequest, или тоже с get. А интерфейс, кажется, можно назвать просто User - он же будет по всему проекту использоваться, а данные с сервера не так принципиально, они фактически в паре методов используются - UserFromServer например. Ну это на первый взгляд так, общий смысл - чтобы было понятно сходу. UserDTO я сходу не понял.

2023-01-29 20:22 UTC, UnidentifiedRaccoon commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
1. Замена ```useEffect``` на ```if(!isAuthorized) checkUser().unwrap().then(...)```. 
При повторном вызове useAuth() (если первый раз сервер не определил пользователя), снова произойдет запрос, (хотя с очевидно что ответ сервера будет отрицательный)

2. Если используем внутри useEffect вместо isFirstCall
```
  useEffect(() => {
    if (!isAuthorized) {
      checkUser().unwrap().then(() => {
        dispatch(setAuthorized({isAuthorized: true}))
      }).catch(e => console.error(e.message))
    }
  }, [isAuthorized])
```
Кода больше чем в 1 примере, но решилась проблема с повторным запросом при вызове useAuth.
При этом когда пользователь разлогиниться, isAuthorized станет = false, сработает useEffect и мы выполним запрос к серверу на получение данных пользователя (хотя мы только что разлогинились и сервер очевидно ответит user is not authorized) - это лишний запрос


Вероятно можно пренебречь лишними запросами, но описать логику так, чтобы это было компактно и без лишних запросов я не смог

2023-01-29 20:34 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
вместо 
```
export const UserDTO_to_User = (data: UserDTO): User
---
export const User_to_UserDTO = (data: User): UserDTO
```

будет 
```
export const mapUserDataFromResponse = (data: UserFromServer): User
---
export const mapUserDataToRequest = (data: User): UserFromServer
```

Нашел для себя 1 вариант более лаконичным и как бы легковесным

> UserDTO я сходу не понял.

Это дело привычки).
Очевидно что не хватает командной документации и фиксации правил именования


Не принципиально могу заменить на 2  вариант

2023-01-29 20:39 UTC, pitonoved approved these changes

2023-01-29 20:39 UTC, pitonoved commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
Так а если не указывать тригер?
```
useEffect(() => {
    if (!isAuthorized) {
      ...
    }
  }, [])
```
Если заморочки, то черт с ним

2023-01-29 20:46 UTC, UnidentifiedRaccoon commented on packages/client/src/app/hooks/useAuth.ts
>  let isFirstCall = true
Не пробовал. Знаю что за такое по рукам бьют. Но почитаю и вернусь с конкретным ответом

2023-01-29 20:47 UTC, UnidentifiedRaccoon commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
Хотел бы по этому вопросу созвониться в пачке.

2023-01-29 23:47 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +    if (isResponseOk(response)) return UserDTO_to_User(response.data)
Redux style guide. Так что предлагаю остановиться на thunk'ax
![image](https://user-images.githubusercontent.com/50448502/215362861-e80df5e4-9178-4d29-8f0e-e9719b23f14d.png)
https://redux.js.org/style-guide/#structure-files-as-feature-folders-with-single-file-logic

2023-02-02 15:22 UTC, UnidentifiedRaccoon commented on packages/client/src/app/store/auth/authThunks.ts
> +    const response = await AuthController.signIn(data)
Вопрос решен. Коммит 5622d72e19c52d73d326a78e36f2ba384f624d8c

2023-02-02 20:58 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/UserController/UserController.ts
> +import {UserDTO_to_User} from "./UserDTO_to_User";
От snake_case избавился, но в общем решил все-таки не менять стиль наименования

2023-02-03 10:32 UTC, kxnkxv approved these changes

2023-02-03 10:32 UTC, kxnkxv commented on packages/client/src/app/Controllers/API.ts
> +
А почему не через Axios.create?

2023-02-03 10:32 UTC, kxnkxv commented on packages/client/src/app/Router/Router.tsx
> +
```suggestion
```

2023-02-04 10:34 UTC, UnidentifiedRaccoon commented on packages/client/src/app/Controllers/API.ts
> +
Не понял вопрос
Почему самописная обертка в виде класса API вокруг Axios.create?
Ну потому так
````
API.get({url: ..., data: ...})
````
Удобней чем так
```
 Axios.create(
  { 
    method: 'get'
    withCredentials: true,
    headers: {
      ...Headers.json
    },
    url: ...
    data: ...
  }
).interceptors.request.use(response => response, function (error) {
  // outside the 2xx range
  const reason = error.response.data.reason
  if (reason) return Promise.reject(new Error(reason));
  return Promise.reject(error);
}, { synchronous: true })
  .then(({data}) => data)
```
И даже если я выношу повторы в baseTransport все равно 1 вариант удобней в сравнении с этим
```
baseTransport.create({method: 'get', url: ..., data: ...}).then(({data}) => data)
```

2023-02-05 05:37 UTC, merged